# Generated by Django 5.1.3 on 2024-11-11 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_tag_question_tags_remove_answer_text1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='nickname',
        ),
    ]
